version: '3.9'
services:
  mongo_db:
    container_name: mongo_docker_3 #opcional
    image: mongo:latest
    ports: 
      - 27020:27017
    volumes:
      - /d/DOCKER/MONGO:/data/db  #directorio local : docker (/data/db)

  api:
    build: .
    ports: 
      - 8080:8080 # puerto local: puerto docker
    environment:
      MONGO_URI: mongodb://mongo_db:27017/coderhouse
    depends_on:
      - mongo_db