const products = [
    { name: "Yerba Mate", price: 1500, stock: 500 , section: "comestibles", active: true},
    { name: "Yerba Orgánica", price: 1500, stock: 500 , section: "comestibles", active: true},
    { name: "Yerba Compuesta", price: 1500, stock: 500 , section: "comestibles", active: true},
    { name: "Café", price: 1500, stock: 450 , section: "comestibles", active: true},
    { name: "Té común", price: 1500, stock: 200 , section: "comestibles", active: true},
    { name: "Té de hierbas", price: 1500, stock: 200 , section: "comestibles", active: true},
    { name: "Té de manzanilla", price: 1500, stock: 200 , section: "comestibles", active: true},
    { name: "Té de boldo", price: 1500, stock: 200 , section: "comestibles", active: true},
    { name: "Mate Cocido", price: 1500, stock: 100 , section: "comestibles", active: true},
    { name: "Azúcar", price: 1200, stock: 100, section: "comestibles", active: true},
    { name: "Dulce de leche", price: 1200, stock: 450 , section: "comestibles", active: true},
    { name: "Galletitas", price: 1200, stock: 500 , section: "comestibles", active: true},
    { name: "Aceite", price: 1200, stock: 100 , section: "comestibles", active: false},
    { name: "Harina", price: 350, stock: 450, section: "comestibles", active: false},
    { name: "Manteca", price: 350, stock: 500 , section: "comestibles", active: false},
    { name: "Mermelada de durazno", price: 350, stock: 450 , section: "comestibles", active: false},
    { name: "Dentifrico", price: 350, stock: 100 , section: "comestibles", active: false},
    { name: "Agua Mineral", price: 740, stock: 100, section: "bebidas", active: true},
    { name: "Vino", price: 740, stock: 50 , section: "bebidas", active: true},
    { name: "Cerveza", price: 740, stock: 100 , section: "bebidas", active: true},
    { name: "Gancia", price: 740, stock: 200 , section: "bebidas", active: true},
    { name: "Fernet", price: 2300, stock: 100, section: "bebidas", active: true},
    { name: "Gaseosa", price: 2300, stock: 450 , section: "bebidas", active: true},
    { name: "Leche", price: 2300, stock: 100 , section: "comestibles", active: true},
    { name: "Crema", price: 2300, stock: 500 , section: "comestibles", active: true},
    { name: "Yogurt", price: 480, stock: 100 , section: "comestibles", active: true},
    { name: "Pan", price: 480, stock: 450 , section: "comestibles", active: true},
    { name: "Alfajor", price: 480, stock: 200 , section: "comestibles", active: true},
    { name: "Facturas", price: 480, stock: 100 , section: "comestibles", active: true},
    { name: "Cloro", price: 480, stock: 100 , section: "limpieza", active: true},
    { name: "Detergente", price: 480, stock: 100 , section: "limpieza", active: true}
  ];
  